# Generated by Django 4.1.2 on 2022-11-24 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(editable=False, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_type', models.CharField(choices=[('admin', 'admin'), ('prof', 'prof'), ('student', 'student')], default='student', max_length=50)),
            ],
        ),
    ]
