# Generated by Django 4.1.2 on 2022-11-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_email_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='password', max_length=32),
        ),
    ]
