# Generated by Django 4.1.2 on 2022-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_email_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='user_name', editable=False, max_length=32),
        ),
    ]
