# Generated by Django 4.1.2 on 2022-11-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_email_alter_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='user_name', max_length=32),
        ),
    ]
