# Generated by Django 4.1.2 on 2022-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('admin', 'admin'), ('prof', 'prof'), ('student', 'student')], default='student', max_length=50),
        ),
    ]
