# Generated by Django 4.1.2 on 2022-11-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_id_profile'),
        ('profiles', '0010_alter_profile_user_name'),
    ]

    operations = [
    ]
