# Generated by Django 4.1.2 on 2022-11-19 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_merge_20221119_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_profile',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
