# Generated by Django 4.1.2 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user_name'),
        ('profiles', '0012_alter_profile_id_profile'),
    ]

    operations = [
    ]
