# Generated by Django 4.1.2 on 2022-11-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('students', '0003_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, default='first_name', max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='grp_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='last_name', max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='sect_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
    ]
