# Generated by Django 4.1.2 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_first_name_alter_student_last_name'),
        ('students', '0008_alter_student_profile'),
    ]

    operations = [
    ]
