# Generated by Django 4.1.2 on 2022-11-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_mod', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('mod_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
