# Generated by Django 4.1.2 on 2022-11-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user_name'),
        ('profs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
