# Generated by Django 4.1.2 on 2022-11-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0002_prof_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='password',
        ),
    ]
