# Generated by Django 4.1.2 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0002_alter_prof_profile'),
        ('profs', '0004_alter_prof_profile'),
    ]

    operations = [
    ]
