# Generated by Django 4.1.2 on 2022-11-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sess_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionApps.sessiondate'),
        ),
    ]
