# Generated by Django 4.1.2 on 2022-11-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionApps', '0002_alter_session_sess_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='schedule',
        ),
    ]
