# Generated by Django 4.1.2 on 2022-11-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('profs', '0001_initial'),
        ('modules', '0001_initial'),
        ('classrooms', '0001_initial'),
        ('sessionApps', '0003_remove_session_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiondate',
            old_name='date_time',
            new_name='sess_date',
        ),
        migrations.AlterField(
            model_name='session',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom'),
        ),
        migrations.AlterField(
            model_name='session',
            name='grp_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.group'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id_mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profs.prof'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sect_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
    ]
