# Generated by Django 4.1.2 on 2022-11-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionApps', '0004_rename_date_time_sessiondate_sess_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sess_date',
            new_name='date',
        ),
    ]
