# Generated by Django 4.1.2 on 2022-12-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionApps', '0005_rename_sess_date_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='SessionDate',
        ),
    ]
