# Generated by Django 4.1.2 on 2022-12-05 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionApps', '0006_alter_session_date_delete_sessiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 5, 12, 22, 26, 349365, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
