# Generated by Django 4.1.2 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionApps', '0002_rename_id_grp_session_grp_num_and_more'),
        ('sessionApps', '0007_session_created_date'),
    ]

    operations = [
    ]
