# Generated by Django 4.1.2 on 2022-11-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('classroom_code', models.IntegerField()),
                ('classroom_type', models.CharField(blank=True, choices=[('L', 'L'), ('A', 'A'), ('S', 'S')], default='L', max_length=2)),
            ],
        ),
    ]
