# Generated by Django 4.1.2 on 2022-11-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(choices=[('L', 'L'), ('A', 'A'), ('S', 'S')], max_length=2),
        ),
    ]
