# Generated by Django 4.1.2 on 2022-11-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='id_sect',
            new_name='sect_num',
        ),
    ]
