# Generated by Django 4.1.2 on 2022-11-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_rename_sect_num_group_id_sect_group_id_grp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id_grp',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id_sect',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
