# Generated by Django 4.1.2 on 2022-11-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_group_id_grp_alter_section_id_sect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id_sect',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
