# Generated by Django 4.1.2 on 2022-11-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApps', '0002_remove_admin_user_name_admin_profile_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
    ]
