# Generated by Django 4.1.2 on 2022-11-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApps', '0003_remove_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
