# Generated by Django 4.1.2 on 2022-11-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApps', '0004_remove_admin_email_remove_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, default='first_name', max_length=32),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, default='last_name', max_length=32),
        ),
    ]
