# Generated by Django 4.1.2 on 2022-11-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApps', '0007_alter_admin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
