# Generated by Django 4.1.2 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApps', '0002_alter_admin_profile'),
        ('adminApps', '0008_alter_admin_first_name_alter_admin_last_name'),
    ]

    operations = [
    ]
