# Generated by Django 4.1.2 on 2022-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusion',
            name='id_exc',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
