# Generated by Django 4.1.2 on 2022-11-24 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id_just', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('just_doc', models.ImageField(blank=True, default='justifications/default.jpg', null=True, upload_to='justifications/')),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('refused', 'refused'), ('hold', 'hold')], default='hold', max_length=10)),
                ('id_abs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.absence')),
            ],
        ),
    ]
