# Generated by Django 4.1.2 on 2022-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='id_just',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
