# Generated by Django 4.1.2 on 2022-11-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0002_alter_justification_id_just'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='just_doc',
            field=models.FileField(blank=True, upload_to='justifications'),
        ),
        migrations.AddField(
            model_name='justification',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('refused', 'refused'), ('hold', 'hold')], default='hold', max_length=10),
        ),
    ]
