# Generated by Django 4.1.2 on 2022-11-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0003_justification_just_doc_justification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='just_doc',
            field=models.ImageField(blank=True, null=True, upload_to='justifications/'),
        ),
    ]
