# Generated by Django 4.1.2 on 2022-11-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0004_alter_justification_just_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='just_doc',
            field=models.ImageField(blank=True, default='justifications/default.jpg', null=True, upload_to='justifications/'),
        ),
    ]
