# Generated by Django 4.1.2 on 2022-11-24 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('classrooms', '0001_initial'),
        ('sections', '0001_initial'),
        ('profs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_sch', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('td', 'td'), ('tp', 'tp'), ('cour', 'cour')], max_length=5)),
                ('cell', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25)])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('grp_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.group')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profs.prof')),
                ('sect_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.section')),
            ],
        ),
    ]
