# Generated by Django 4.1.2 on 2022-11-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('td', 'td'), ('tp', 'tp'), ('cours', 'cours')], max_length=5),
        ),
    ]
