# Generated by Django 4.1.2 on 2022-11-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_rename_id_grp_schedule_grp_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='box',
            new_name='cell',
        ),
    ]
