# Generated by Django 4.1.2 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_type'),
        ('schedules', '0004_alter_schedule_cell'),
    ]

    operations = [
    ]
